### ISSUE TITLE
一个爆破场景

### ISSUE THREAD

**Issue by sv3nbeast** [smxiazi/NEW_xp_CAPTCHA#11]
### 获得验证码:
访问验证码url，返回验证码图片和对应的uuid
### 验证码机制:
输入验证码 + 输入验证码对应的uuid = 验证码验证成功

目前遇到此类的验证码验证机制较多，不知道师傅是否有加入此功能的打算。

**Comment by smxiazi** [comment]
现在更新的4.2支持了
