### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by jinzezhi** [smxiazi/NEW_xp_CAPTCHA#12]
ERROR: Could not find a version that satisfies the requirement onnxruntime (from ddddocr) (from versions: none)
ERROR: No matching distribution found for onnxruntime
这是版本原因嘛，我已经换了3.6.6版本

**Comment by smxiazi** [comment]
python3 -m pip install requests
python3 -m pip install -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com muggle-ocr
python3 -m pip install ddddocr -i https://pypi.tuna.tsinghua.edu.cn/simple

都运行命令安装了吗

**Comment by jinzezhi** [comment]
![image](https://user-images.githubusercontent.com/93123422/178214010-b517276b-66d8-47ff-9f35-aba5654d9d6e.png)
E:\aluyy\aluyy_web\plug-in\burp_cj\yzm>python3 -m pip install ddddocr -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting ddddocr
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/43/f7/febabbc3580e811accf89ca5236c7de0062b07adf535edc66587ff9149cb/ddddocr-1.0.6-py3-none-any.whl (6.9 MB)
ERROR: Could not find a version that satisfies the requirement onnxruntime (from ddddocr) (from versions: none)
ERROR: No matching distribution found for onnxruntime

**Comment by jinzezhi** [comment]
网上没找到解决办法..只好来求教作者

**Comment by smxiazi** [comment]
python3 -m pip install --upgrade pip
更新一下在运行
python3 -m pip install ddddocr -i https://pypi.tuna.tsinghua.edu.cn/simple
试试？

**Comment by smxiazi** [comment]
或者指定版本试试？
python3 -m pip install ddddocr==1.4.3 -i https://pypi.tuna.tsinghua.edu.cn/simple

python3 -m pip install ddddocr==1.3.1 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by smxiazi** [comment]
在不行 可以试试 pip install ddddocr

**Comment by jinzezhi** [comment]
E:\aluyy\aluyy_web\plug-in\burp_cj\yzm>pip install ddddocr
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: ddddocr in e:\aluyy\aluyy_web\app\python\lib\site-packages (1.4.3)
Requirement already satisfied: opencv-python in e:\aluyy\aluyy_web\app\python\lib\site-packages (from ddddocr) (4.6.0.66)
Requirement already satisfied: numpy in e:\aluyy\aluyy_web\app\python\lib\site-packages (from ddddocr) (1.19.5)
Requirement already satisfied: Pillow in e:\aluyy\aluyy_web\app\python\lib\site-packages (from ddddocr) (8.4.0)
Requirement already satisfied: onnxruntime in e:\aluyy\aluyy_web\app\python\lib\site-packages (from ddddocr) (1.10.0)
Requirement already satisfied: flatbuffers in e:\aluyy\aluyy_web\app\python\lib\site-packages (from onnxruntime->ddddocr) (2.0)
Requirement already satisfied: protobuf in e:\aluyy\aluyy_web\app\python\lib\site-packages (from onnxruntime->ddddocr) (4.21.0)

这样应该就是成功了吧

**Comment by smxiazi** [comment]
我又特意去下载了个3.6.6的版本的 确认没啥问题

**Comment by jinzezhi** [comment]
是的呀

**Comment by jinzezhi** [comment]
**C:\Users\12831>python3 -m pip install requests**
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: requests in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (2.28.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (1.26.10)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests) (2022.6.15)

**C:\Users\12831>python3 -m pip install -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com muggle-ocr**
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: muggle-ocr in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (1.0.3)
Requirement already satisfied: tensorflow>=1.14 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from muggle-ocr) (2.9.1)
Requirement already satisfied: numpy in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from muggle-ocr) (1.23.1)
Requirement already satisfied: pillow in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from muggle-ocr) (9.2.0)
Requirement already satisfied: opencv-python in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from muggle-ocr) (4.6.0.66)
Requirement already satisfied: pyyaml in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from muggle-ocr) (6.0)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\site-packages (from tensorflow>=1.14->muggle-ocr) (58.1.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (1.1.0)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (0.4.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (1.47.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (1.1.2)
Requirement already satisfied: h5py>=2.9.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (3.7.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (4.3.0)
Requirement already satisfied: six>=1.12.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (1.16.0)
Requirement already satisfied: keras<2.10.0,>=2.9.0rc0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (2.9.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (0.2.0)
Requirement already satisfied: packaging in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (21.3)
Requirement already satisfied: flatbuffers<2,>=1.12 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (1.12)
Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (2.9.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (14.0.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (0.26.0)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (3.19.4)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (1.14.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (3.3.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (1.6.3)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (1.1.0)
Requirement already satisfied: tensorboard<2.10,>=2.9 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorflow>=1.14->muggle-ocr) (2.9.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from astunparse>=1.6.0->tensorflow>=1.14->muggle-ocr) (0.37.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (2.28.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (1.8.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (3.3.7)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (0.6.1)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (2.1.2)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (2.9.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (0.4.6)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from packaging->tensorflow>=1.14->muggle-ocr) (3.0.9)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (4.8)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (5.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (1.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (1.26.10)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (2022.6.15)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\12831\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow>=1.14->muggle-ocr) (3.2.0)

**C:\Users\12831>python3 -m pip install ddddocr -i https://pypi.tuna.tsinghua.edu.cn/simple**
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting ddddocr
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/43/f7/febabbc3580e811accf89ca5236c7de0062b07adf535edc66587ff9149cb/ddddocr-1.0.6-py3-none-any.whl (6.9 MB)
ERROR: Could not find a version that satisfies the requirement onnxruntime (from ddddocr) (from versions: none)
ERROR: No matching distribution found for onnxruntime

**Comment by jinzezhi** [comment]
这三条命令 ，最后一条就报错了

**Comment by smxiazi** [comment]
[Windows x86-64 executable installer](https://www.python.org/ftp/python/3.6.6/python-3.6.6-amd64.exe)

重新下载python3.6.6 然后利用这个把之前的卸载了，然后继续安装一下。

**Comment by jinzezhi** [comment]
ok啦 多谢师傅指教 辛苦

**Comment by smxiazi** [comment]
我已经弄个集成包了
正在上传github，直接下载免安装，直接用。

**Comment by jinzezhi** [comment]
换别的第三方呢

**Comment by jinzezhi** [comment]
可以换其他第三方接口吗师傅

**Comment by smxiazi** [comment]
写死了，固定了，改不了了
