### ISSUE TITLE
no generators defined

### ISSUE THREAD

**Issue by PonusJang** [smxiazi/NEW_xp_CAPTCHA#15]
java version "1.8.0_341"

burpsuit 1.7.37  插件加载正常  server正常启动

但是intruder 显示 no generators defined

这是啥问题

**Comment by smxiazi** [comment]
导入插件了吗。配置了字典里吗？截图看看？

**Comment by PonusJang** [comment]
![image](https://user-images.githubusercontent.com/24632564/183352053-ce9869ea-d43c-4ced-b628-18b0e8eb16e8.png)
![image](https://user-images.githubusercontent.com/24632564/183352151-d2ea7160-323b-45ce-bade-94f36cf58b0a.png)


导入信息无   intruder payload generators   = 1

**Comment by smxiazi** [comment]
微信 wang_z_h_ 加我

**Comment by smxiazi** [comment]
已解决，挂了代理的原因。
