### ISSUE TITLE
验证码请求包识别是否只支持GET请求方法

### ISSUE THREAD

**Issue by djnodt** [smxiazi/NEW_xp_CAPTCHA#17]
![image](https://user-images.githubusercontent.com/30315200/201807232-5fc0720f-74fd-4aa2-b575-a41fbbbbe113.png)
该验证码请求，按照README中JSON高级设置下，未能识别验证码

**Comment by smxiazi** [comment]
目前是只支持get类型，可以查看这篇https://mp.weixin.qq.com/s/iA9XEuoTyjOAxSDoIJsm5Q文章，这个文章可以达到post类型的效果，后续可能会直接添加到插件里面。
