### ISSUE TITLE
error：瞎跑接口好像出问题了？

### ISSUE THREAD

**Issue by Look4your** [smxiazi/NEW_xp_CAPTCHA#18]
macos python3.10 服务启动正常，访问127.0.0.1:8899正常，插件获取不到验证码，提示error：瞎跑接口好像出问题了？

![image](https://user-images.githubusercontent.com/64736780/210940953-587cddaf-fbf7-4147-be05-e01051ee409f.png)

**Comment by smxiazi** [comment]
你burp是不是配置了代理，导致访问不到本地的127.0.0.1的8899端口

**Comment by Look4your** [comment]
确实，感谢大佬

**Comment by ViewOweiV** [comment]
配置没有问题，爆破线程设置1，验证码识别一和二都使用了，都是error:识别失败！ 8899端口访问正常，不知是啥问题，求大佬解答。

![图片](https://user-images.githubusercontent.com/69718545/217729927-2410d14a-1aab-4195-b00a-b7b08eb0083c.png)

![图片](https://user-images.githubusercontent.com/69718545/217729789-b96aca49-4354-4b73-9551-4ec1f18cf8c6.png)

**Comment by smxiazi** [comment]
在插件里面填写的地址错了，填写的是验证码的url地址。

**Comment by smxiazi** [comment]
右键-检查-网络 然后点击刷新验证码，就能看到验证码的url地址了

**Comment by ViewOweiV** [comment]
可以了，谢谢大佬，是我太不细心了哈哈哈

**Comment by Yoop-yes** [comment]
如何burp设置代理也能请求到 python脚本
