### ISSUE TITLE
NEW_xp_CAPTCHA win64 python环境完整版找不到CAPT.jdk

### ISSUE THREAD

**Issue by songlida** [smxiazi/NEW_xp_CAPTCHA#23]
大佬我下载你那个NEW_xp_CAPTCHA win64 python环境完整版了但是不知道怎么才能导到bp里面求指导  找不到.jdk的那个文件

**Comment by smxiazi** [comment]
插件在这里下载
https://github.com/smxiazi/NEW_xp_CAPTCHA/releases

记得替换一下那个server.py这个脚本
