### ISSUE TITLE
瞎跑端口不对

### ISSUE THREAD

**Issue by songlida** [smxiazi/NEW_xp_CAPTCHA#24]
验证码1：taadz2
验证码1：wbxht
验证码1：8w3xt
验证码1：abs6uz
验证码1：jdpiaa
验证码1：gep39h
error：瞎跑接口无应答，是不是配置错地址了？

error：瞎跑接口无应答，是不是配置错地址了？

error：瞎跑接口无应答，是不是配置错地址了
间隔着不知道怎么解决

**Comment by songlida** [comment]
一段验证码一段error

**Comment by q1e4t6** [comment]
请问你这个问题解决了嘛 我现在也遇到这个问题了...

**Comment by q1e4t6** [comment]
> 一段验证码一段error

请问你这个问题解决了嘛 我现在也遇到这个问题了...

**Comment by smxiazi** [comment]
这么奇怪吗？ 是本地起的吗？

**Comment by smxiazi** [comment]
重启一下 python脚本应该就可以了

**Comment by q1e4t6** [comment]
重启了一次，但是好了十几分钟又出现了刚才的问题..


| |
闫明宇
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月27日 10:28 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [smxiazi/NEW_xp_CAPTCHA] 瞎跑端口不对 (Issue #24) |

这么奇怪吗？ 是本地起的吗？
