### ISSUE TITLE
win10安装muggle_ocr报错

### ISSUE THREAD

**Issue by uzesi** [smxiazi/NEW_xp_CAPTCHA#27]
用的python3.6.5。更新了pip，还是不行
![HTL5J T(DL LDZ3AS)HV`_X](https://github.com/smxiazi/NEW_xp_CAPTCHA/assets/17883546/992e7214-1c18-4ddb-9a9a-acf848194652)

**Comment by smxiazi** [comment]
直接下来我打包好的环境集成包吧

**Comment by smxiazi** [comment]
如果是用win系统可以直接下载打包好的环境,内置python3.6.6版本以及下载好对应的模块 NEW_xp_CAPTCHA win64 python环境完整版.rar
链接: https://pan.baidu.com/s/1U0ZRjtxdqmNYF0b_O-6B1Q 提取码: tfi5
