### ISSUE TITLE
二维码失效了，博客框架是用WordPress搭建的嘛？

### ISSUE THREAD

**Issue by LiuSirs** [smxiazi/NEW_xp_CAPTCHA#3]
~

**Comment by smxiazi** [comment]
群已经满200人了  扫码进不来了  博客是用纯静态搭建的

**Comment by LiuSirs** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    瞎哥，有没有可能加个微信，拉我进去交流学习一下，我微信：lx60600另外，博客的静态文件-项目源码能不能发我学习一下，Wordpress搭建的感觉页面结构都比较复杂，感觉您博客模版比较简洁。
    
        
            
        
    
    
          
        
            —————————Best Regards / 刘鑫
        
    
     
    

    在2021年05月10日 ***@***.***> 写道： 




群已经满200人了  扫码进不来了  博客是用纯静态搭建的
