### ISSUE TITLE
Intruder 设置了payload processing时，识别的验证码无法赋值到关键字

### ISSUE THREAD

**Issue by urq-1** [smxiazi/NEW_xp_CAPTCHA#31]
{"name":"admin","mailCode":"","password":"§7c4a8d09ca3762af61e59520943dc26494f8941b§","captcha":"@xiapao@1@","oldPass":"","confirmPass":"","newPass":""}

password payload设置了md5之后，intruder发送的请求就没有被识别的验证码字符串赋值了，取消payload processing之后就正常的。

**Comment by smxiazi** [comment]
会不会 是你的 "captcha":"@Xiapao@1@"  设置了X是大写，应该是@xiapao@1@
