### ISSUE TITLE
验证码识别都是正确的，但是服务端响应一直反馈验证码报错。辛苦大佬帮忙看看是什么原因

### ISSUE THREAD

**Issue by TheNorth-sec** [smxiazi/NEW_xp_CAPTCHA#32]
1、xiapao识别结果很准确
![image](https://github.com/user-attachments/assets/47d963df-d56c-4869-9e3f-5c29ded99a6c)

2、服务端一直反馈验证码错误
![image](https://github.com/user-attachments/assets/a7d06aec-14d7-414a-9d64-d6ed849967e9)

**Comment by smxiazi** [comment]
目测你这个是在你的登录请求包里面没有带cookie，验证码判断一般是用的cookie，部分会有用uuid去验证，或者线程没有设置成1，导致验证码刷新后还没使用又被刷新，
