### ISSUE TITLE
访问127...刷新一次BP才会爆破一次

### ISSUE THREAD

**Issue by llcharming00** [smxiazi/NEW_xp_CAPTCHA#34]
burpsuite爆破时，不会自动载入，在浏览器访问127.0.0.1:8899,浏览器器刷新一次才会爆破一次，大佬们是不是要改哪里的设置呀

**Comment by smxiazi** [comment]
应该你理解错误了，你可以看插件的界面，最新的识别结果都在上面实时显示，他有没有有一直在跑，就看他有没有一直显示，浏览器访问127.0.0.1:8899这个只是为了给看看验证码识别的准不准，你每次刷新他都会把当前跑的近50个的验证码给你查看，你不打开该界面，插件依然会运行。
