### ISSUE TITLE
数据包中验证码没有被赋值

### ISSUE THREAD

**Issue by tangweiv** [smxiazi/NEW_xp_CAPTCHA#35]
![图片](https://github.com/user-attachments/assets/221dc9f3-57ee-436d-a9d7-0cb1f6dfa0d8)

这是什么情况啊

**Comment by smxiazi** [comment]
这里不会显示验证码的，但是实际上发给服务器的是已经替换掉这个的了，你可以安装个logger插件，看看burp的流量。
