### ISSUE TITLE
识别率低哦老哥.

### ISSUE THREAD

**Issue by Lundy8899** [smxiazi/NEW_xp_CAPTCHA#5]
识别了4个.4个全错....
4个数字的验证码
3438 识别 z490
6160 识别 b160
3899 识别3b9g
3670 识别3570

**Comment by smxiazi** [comment]
某些验证码 识别率特别低  你可以试试 https://github.com/smxiazi/xp_CAPTCHA 这个是调用收费的接口 1块钱可以识别500次
