### ISSUE TITLE
code 404, message Page not Found!

### ISSUE THREAD

**Issue by Leontree** [smxiazi/NEW_xp_CAPTCHA#6]
![image](https://user-images.githubusercontent.com/25098297/131320076-eee60bf9-0e0e-4418-9a28-c261cdae5824.png)
![1630316250(1)](https://user-images.githubusercontent.com/25098297/131319408-8fe675c0-b7a2-40f8-bb6f-2779ba6c1abe.png)
老哥，这个代码有啥问题么？

**Comment by smxiazi** [comment]
代码67行 url后面多了个空格
